Change from isdefined function to @isdefined macro
In Julia v0.7.0 the function form is deprecated and results in what looks like a parse error:

```
julia> Pkg.build("Conda")
INFO: Building Conda
=================================================================[ ERROR: Conda ]==================================================================

LoadError: type CodeInfo has no field def
in expression starting at /Users/patrick/.julia/v0.7/Conda/deps/build.jl:7

===================================================================================================================================================

=================================================================[ BUILD ERRORS ]==================================================================

WARNING: Conda had build errors.

 - packages with build errors remain installed in /Users/patrick/.julia/v0.7
 - build the package(s) and all dependencies with `Pkg.build("Conda")`
 - build a single package by running its `deps/build.jl` script

===================================================================================================================================================
```